import 'dart:convert';

import 'package:appflowy/startup/tasks/deeplink/deeplink_handler.dart';
import 'package:appflowy_backend/log.dart';
import 'package:appflowy_backend/protobuf/flowy-error/errors.pb.dart';
import 'package:appflowy_result/appflowy_result.dart';
import 'package:http/http.dart' as http;
import 'package:appflowy/env/cloud_env.dart';
import 'package:appflowy/startup/startup.dart' show getIt;
import 'package:appflowy/user/application/auth/auth_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:appflowy/features/workspace/logic/workspace_bloc.dart';
import 'package:appflowy/shared/settings/show_settings.dart'
    show showSettingsDialog;
import 'package:appflowy/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart'
    show ClipboardService;
import 'package:appflowy/startup/tasks/app_widget.dart' show AppGlobals;
import 'package:appflowy/workspace/presentation/widgets/dialogs.dart'
    show showToastNotification;
import 'package:appflowy/workspace/application/settings/settings_dialog_bloc.dart'
    show SettingsPage;
import 'package:appflowy/workspace/presentation/home/menu/sidebar/workspace/workspace_notifier.dart';
import 'package:appflowy/startup/tasks/appflowy_cloud_task.dart'
    show appflowyDeepLinkSchema;
import 'package:appflowy/startup/tasks/deeplink/deeplink_loading_overlay.dart';
import 'package:universal_platform/universal_platform.dart';

/// Handles invite deep links generated by the share page:
/// `ponynotes://invite?q=...&ws=...` or the equivalent trusted HTTPS link.
///
/// `code/workspaceId` is kept as a legacy alias so links generated by older
/// client versions continue to work after an upgrade.
class AppflowyInviteDeepLinkHandler extends DeepLinkHandler<void> {
  static const inviteHost = 'invite';
  static const inviteWebPath = 'invited';
  static const inviteWebHosts = <String>{
    'www.xiaomabiji.com',
    'www.xiaomabiji.io',
    'test.www.xiaomabiji.com',
    'test.www.xiaomabiji.io',
  };
  static const paramCode = 'q';
  static const paramWs = 'ws';
  static const legacyParamCode = 'code';
  static const legacyParamWs = 'workspaceId';

  @override
  bool canHandle(Uri uri) {
    final isProtocolInvite = uri.scheme == appflowyDeepLinkSchema &&
        (uri.host == inviteHost ||
            (uri.pathSegments.isNotEmpty &&
                uri.pathSegments.first == inviteHost));
    if (!isProtocolInvite && !isTrustedInviteWebUri(uri)) {
      return false;
    }

    final code = _firstNonEmpty(uri.queryParameters, [
      paramCode,
      legacyParamCode,
    ]);
    final workspaceId = _firstNonEmpty(uri.queryParameters, [
      paramWs,
      legacyParamWs,
    ]);
    return code != null && workspaceId != null;
  }

  /// Returns true only for the HTTPS invite links advertised by AASA.
  ///
  /// Keeping this check strict prevents unrelated web links from being
  /// interpreted as an invite and sent to the join endpoint.
  static bool isTrustedInviteWebUri(Uri uri) {
    if (uri.scheme != 'https' ||
        !inviteWebHosts.contains(uri.host.toLowerCase())) {
      return false;
    }
    return uri.path == '/$inviteWebPath' || uri.path == '/$inviteWebPath/';
  }

  @override
  Future<FlowyResult<void, FlowyError>> handle({
    required Uri uri,
    required DeepLinkStateHandler onStateChange,
  }) async {
    onStateChange(this, DeepLinkState.loading);
    // Android 端使用 showWhenReady 等待 overlay 就绪，避免黑屏
    if (UniversalPlatform.isAndroid) {
      await DeepLinkLoadingOverlay.showWhenReady(message: '正在加入协作工作区...');
    } else {
      DeepLinkLoadingOverlay.show(message: '正在加入协作工作区...');
    }
    try {
      final code = _firstNonEmpty(uri.queryParameters, [
        paramCode,
        legacyParamCode,
      ]);
      final ws = _firstNonEmpty(uri.queryParameters, [
        paramWs,
        legacyParamWs,
      ]);
      if (code == null || ws == null) {
        return FlowyResult.failure(FlowyError(msg: 'Missing code or ws'));
      }

      // Resolve base URL from DI
      final sharedEnv = getIt<AppFlowyCloudSharedEnv>();
      final baseUrl = sharedEnv.appflowyCloudConfig.base_url;
      // backend exposes join-by-invite-code as /api/workspace/join-by-invite-code
      final url = Uri.parse('$baseUrl/api/workspace/join-by-invite-code');

      // Try to attach Authorization header if available
      final headers = <String, String>{'Content-Type': 'application/json'};
      try {
        final authService = getIt<AuthService>();
        final userRes = await authService.getUser();
        userRes.fold((userProfile) {
          final raw = userProfile.token;
          if (raw.isNotEmpty) {
            String? accessToken;
            try {
              final decoded = jsonDecode(raw);
              if (decoded is Map<String, dynamic>) {
                accessToken = decoded['access_token'] as String?;
              }
            } catch (_) {
              accessToken = raw;
            }
            if (accessToken != null && accessToken.isNotEmpty) {
              headers['Authorization'] = 'Bearer $accessToken';
            }
          }
        }, (err) {
          // ignore - no user available
        });
      } catch (_) {}

      final resp = await http
          .post(
            url,
            headers: headers,
            body: jsonEncode({'code': code}),
          )
          .timeout(const Duration(seconds: 10));

      if (resp.statusCode == 200) {
        // try to extract returned workspace id
        String? joinedWorkspaceId;
        try {
          final decoded = jsonDecode(resp.body);
          if (decoded is Map) {
            joinedWorkspaceId =
                decoded['data']?['workspace_id'] ?? decoded['workspace_id'];
          }
        } catch (_) {}
        joinedWorkspaceId ??= ws;

        Log.info(
            '[InviteDeepLink] Joined workspace $joinedWorkspaceId via invite $code');
        onStateChange(this, DeepLinkState.finish);
        DeepLinkLoadingOverlay.hide();

        // Android 端使用 addPostFrameCallback 确保 UI 完全就绪后再显示对话框
        if (UniversalPlatform.isAndroid) {
          WidgetsBinding.instance.addPostFrameCallback((_) async {
            // 短暂延迟，确保App完全初始化
            await Future.delayed(const Duration(milliseconds: 300));

            final context = AppGlobals.rootNavKey.currentState?.context;
            if (context != null && context.mounted) {
              // show confirmation dialog
              await showDialog(
                context: context,
                builder: (dialogCtx) {
                  return AlertDialog(
                    title: const Text('已加入工作区'),
                    content: Text('已成功加入工作区 $joinedWorkspaceId，是否前往查看？'),
                    actions: [
                      TextButton(
                        onPressed: () {
                          Navigator.of(dialogCtx).pop();
                        },
                        child: const Text('稍后'),
                      ),
                      TextButton(
                        onPressed: () {
                          Navigator.of(dialogCtx).pop();
                          // UserWorkspaceBloc is scoped below the root navigator.
                          // Use the existing notifier so the sidebar dispatches the
                          // switch with the correct workspace type and retry logic.
                          openWorkspaceNotifier.value = WorkspaceNotifyValue(
                            workspaceId: joinedWorkspaceId,
                          );
                        },
                        child: const Text('前往查看'),
                      ),
                    ],
                  );
                },
              );
            } else {
              Log.error('[InviteDeepLink] Context not available for dialog after join success');
            }
          });
        } else {
          // 其他平台保持原有逻辑
          final context = AppGlobals.rootNavKey.currentState?.context;
          if (context != null) {
            // show confirmation dialog
            await showDialog(
              context: context,
              builder: (dialogCtx) {
                return AlertDialog(
                  title: const Text('已加入工作区'),
                  content: Text('已成功加入工作区 $joinedWorkspaceId，是否前往查看？'),
                  actions: [
                    TextButton(
                      onPressed: () {
                        Navigator.of(dialogCtx).pop();
                      },
                      child: const Text('稍后'),
                    ),
                    TextButton(
                      onPressed: () {
                        Navigator.of(dialogCtx).pop();
                        openWorkspaceNotifier.value = WorkspaceNotifyValue(
                          workspaceId: joinedWorkspaceId,
                        );
                      },
                      child: const Text('前往查看'),
                    ),
                  ],
                );
              },
            );
          }
        }

        return FlowyResult.success(null);
      } else {
        final body = resp.body.isNotEmpty ? resp.body : '';
        Log.error(
            '[InviteDeepLink] join workspace failed: status ${resp.statusCode}, body: $body');
        onStateChange(this, DeepLinkState.error);
        DeepLinkLoadingOverlay.hide();

        // Android 端使用 addPostFrameCallback 确保 UI 完全就绪后再显示错误对话框
        if (UniversalPlatform.isAndroid) {
          WidgetsBinding.instance.addPostFrameCallback((_) async {
            // 短暂延迟，确保App完全初始化
            await Future.delayed(const Duration(milliseconds: 300));

            final context = AppGlobals.rootNavKey.currentState?.context;
            if (context != null && context.mounted) {
              // copy invite code helper
              await showDialog(
                context: context,
                builder: (dialogCtx) {
                  return AlertDialog(
                    title: const Text('加入失败'),
                    content: Text(
                        '自动加入工作区失败：${resp.statusCode} ${body.isNotEmpty ? body : ''}'),
                    actions: [
                      TextButton(
                        onPressed: () async {
                          await getIt<ClipboardService>().setPlainText(code);
                          Navigator.of(dialogCtx).pop();
                          // show toast
                          showToastNotification(message: '邀请码已复制到剪贴板');
                        },
                        child: const Text('复制邀请码'),
                      ),
                      TextButton(
                        onPressed: () {
                          Navigator.of(dialogCtx).pop();
                          // open settings -> members page
                          try {
                            final userProfile =
                                context.read<UserWorkspaceBloc>().state.userProfile;
                            showSettingsDialog(
                                context,
                                userProfile,
                                context.read<UserWorkspaceBloc>(),
                                SettingsPage.member);
                          } catch (e) {
                            // fallback: just open settings dialog
                            final maybeProfile =
                                context.read<UserWorkspaceBloc>().state.userProfile;
                            showSettingsDialog(
                                context,
                                maybeProfile,
                                context.read<UserWorkspaceBloc>(),
                                SettingsPage.member);
                          }
                        },
                        child: const Text('去 人员管理'),
                      ),
                    ],
                  );
                },
              );
            } else {
              Log.error('[InviteDeepLink] Context not available for error dialog');
            }
          });
        } else {
          // 其他平台保持原有逻辑
          final context = AppGlobals.rootNavKey.currentState?.context;
          if (context != null) {
            // copy invite code helper
            await showDialog(
              context: context,
              builder: (dialogCtx) {
                return AlertDialog(
                  title: const Text('加入失败'),
                  content: Text(
                      '自动加入工作区失败：${resp.statusCode} ${body.isNotEmpty ? body : ''}'),
                  actions: [
                    TextButton(
                      onPressed: () async {
                        await getIt<ClipboardService>().setPlainText(code);
                        Navigator.of(dialogCtx).pop();
                        // show toast
                        showToastNotification(message: '邀请码已复制到剪贴板');
                      },
                      child: const Text('复制邀请码'),
                    ),
                    TextButton(
                      onPressed: () {
                        Navigator.of(dialogCtx).pop();
                        // open settings -> members page
                        try {
                          final userProfile =
                              context.read<UserWorkspaceBloc>().state.userProfile;
                          showSettingsDialog(
                              context,
                              userProfile,
                              context.read<UserWorkspaceBloc>(),
                              SettingsPage.member);
                        } catch (e) {
                          // fallback: just open settings dialog
                          final maybeProfile =
                              context.read<UserWorkspaceBloc>().state.userProfile;
                          showSettingsDialog(
                              context,
                              maybeProfile,
                              context.read<UserWorkspaceBloc>(),
                              SettingsPage.member);
                        }
                      },
                      child: const Text('去 人员管理'),
                    ),
                  ],
                );
              },
            );
          }
        }

        return FlowyResult.failure(
            FlowyError(msg: 'Join workspace failed: ${resp.statusCode}'));
      }
    } catch (e, st) {
      Log.error('[InviteDeepLink] Exception: $e', st);
      onStateChange(this, DeepLinkState.error);
      return FlowyResult.failure(FlowyError(msg: 'Exception: $e'));
    } finally {
      DeepLinkLoadingOverlay.hide();
    }
  }

  static String? _firstNonEmpty(
    Map<String, String> parameters,
    List<String> keys,
  ) {
    for (final key in keys) {
      final value = parameters[key]?.trim();
      if (value != null && value.isNotEmpty) {
        return value;
      }
    }
    return null;
  }
}
