// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `entities.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct CreateHandwritingSaberPayloadPB {
    // message fields
    pub view_id: ::std::string::String,
    // message oneof groups
    pub one_of_initial_data: ::std::option::Option<CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CreateHandwritingSaberPayloadPB {
    fn default() -> &'a CreateHandwritingSaberPayloadPB {
        <CreateHandwritingSaberPayloadPB as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data {
    initial_data(::std::vec::Vec<u8>),
}

impl CreateHandwritingSaberPayloadPB {
    pub fn new() -> CreateHandwritingSaberPayloadPB {
        ::std::default::Default::default()
    }

    // string view_id = 1;


    pub fn get_view_id(&self) -> &str {
        &self.view_id
    }
    pub fn clear_view_id(&mut self) {
        self.view_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_view_id(&mut self, v: ::std::string::String) {
        self.view_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_view_id(&mut self) -> &mut ::std::string::String {
        &mut self.view_id
    }

    // Take field
    pub fn take_view_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.view_id, ::std::string::String::new())
    }

    // bytes initial_data = 2;


    pub fn get_initial_data(&self) -> &[u8] {
        match self.one_of_initial_data {
            ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_initial_data(&mut self) {
        self.one_of_initial_data = ::std::option::Option::None;
    }

    pub fn has_initial_data(&self) -> bool {
        match self.one_of_initial_data {
            ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_initial_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.one_of_initial_data = ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_initial_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(_)) = self.one_of_initial_data {
        } else {
            self.one_of_initial_data = ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(::std::vec::Vec::new()));
        }
        match self.one_of_initial_data {
            ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_initial_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_initial_data() {
            match self.one_of_initial_data.take() {
                ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }
}

impl ::protobuf::Message for CreateHandwritingSaberPayloadPB {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.view_id)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.one_of_initial_data = ::std::option::Option::Some(CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(is.read_bytes()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.view_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.view_id);
        }
        if let ::std::option::Option::Some(ref v) = self.one_of_initial_data {
            match v {
                &CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(2, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.view_id.is_empty() {
            os.write_string(1, &self.view_id)?;
        }
        if let ::std::option::Option::Some(ref v) = self.one_of_initial_data {
            match v {
                &CreateHandwritingSaberPayloadPB_oneof_one_of_initial_data::initial_data(ref v) => {
                    os.write_bytes(2, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CreateHandwritingSaberPayloadPB {
        CreateHandwritingSaberPayloadPB::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "view_id",
                |m: &CreateHandwritingSaberPayloadPB| { &m.view_id },
                |m: &mut CreateHandwritingSaberPayloadPB| { &mut m.view_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "initial_data",
                CreateHandwritingSaberPayloadPB::has_initial_data,
                CreateHandwritingSaberPayloadPB::get_initial_data,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CreateHandwritingSaberPayloadPB>(
                "CreateHandwritingSaberPayloadPB",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CreateHandwritingSaberPayloadPB {
        static instance: ::protobuf::rt::LazyV2<CreateHandwritingSaberPayloadPB> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CreateHandwritingSaberPayloadPB::new)
    }
}

impl ::protobuf::Clear for CreateHandwritingSaberPayloadPB {
    fn clear(&mut self) {
        self.view_id.clear();
        self.one_of_initial_data = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CreateHandwritingSaberPayloadPB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateHandwritingSaberPayloadPB {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SaveHandwritingSaberPayloadPB {
    // message fields
    pub view_id: ::std::string::String,
    pub sbn2_bytes: ::std::vec::Vec<u8>,
    pub version: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SaveHandwritingSaberPayloadPB {
    fn default() -> &'a SaveHandwritingSaberPayloadPB {
        <SaveHandwritingSaberPayloadPB as ::protobuf::Message>::default_instance()
    }
}

impl SaveHandwritingSaberPayloadPB {
    pub fn new() -> SaveHandwritingSaberPayloadPB {
        ::std::default::Default::default()
    }

    // string view_id = 1;


    pub fn get_view_id(&self) -> &str {
        &self.view_id
    }
    pub fn clear_view_id(&mut self) {
        self.view_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_view_id(&mut self, v: ::std::string::String) {
        self.view_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_view_id(&mut self) -> &mut ::std::string::String {
        &mut self.view_id
    }

    // Take field
    pub fn take_view_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.view_id, ::std::string::String::new())
    }

    // bytes sbn2_bytes = 2;


    pub fn get_sbn2_bytes(&self) -> &[u8] {
        &self.sbn2_bytes
    }
    pub fn clear_sbn2_bytes(&mut self) {
        self.sbn2_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_sbn2_bytes(&mut self, v: ::std::vec::Vec<u8>) {
        self.sbn2_bytes = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_sbn2_bytes(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.sbn2_bytes
    }

    // Take field
    pub fn take_sbn2_bytes(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.sbn2_bytes, ::std::vec::Vec::new())
    }

    // int64 version = 3;


    pub fn get_version(&self) -> i64 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i64) {
        self.version = v;
    }
}

impl ::protobuf::Message for SaveHandwritingSaberPayloadPB {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.view_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.sbn2_bytes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.view_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.view_id);
        }
        if !self.sbn2_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.sbn2_bytes);
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(3, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.view_id.is_empty() {
            os.write_string(1, &self.view_id)?;
        }
        if !self.sbn2_bytes.is_empty() {
            os.write_bytes(2, &self.sbn2_bytes)?;
        }
        if self.version != 0 {
            os.write_int64(3, self.version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SaveHandwritingSaberPayloadPB {
        SaveHandwritingSaberPayloadPB::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "view_id",
                |m: &SaveHandwritingSaberPayloadPB| { &m.view_id },
                |m: &mut SaveHandwritingSaberPayloadPB| { &mut m.view_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "sbn2_bytes",
                |m: &SaveHandwritingSaberPayloadPB| { &m.sbn2_bytes },
                |m: &mut SaveHandwritingSaberPayloadPB| { &mut m.sbn2_bytes },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "version",
                |m: &SaveHandwritingSaberPayloadPB| { &m.version },
                |m: &mut SaveHandwritingSaberPayloadPB| { &mut m.version },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SaveHandwritingSaberPayloadPB>(
                "SaveHandwritingSaberPayloadPB",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SaveHandwritingSaberPayloadPB {
        static instance: ::protobuf::rt::LazyV2<SaveHandwritingSaberPayloadPB> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SaveHandwritingSaberPayloadPB::new)
    }
}

impl ::protobuf::Clear for SaveHandwritingSaberPayloadPB {
    fn clear(&mut self) {
        self.view_id.clear();
        self.sbn2_bytes.clear();
        self.version = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SaveHandwritingSaberPayloadPB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SaveHandwritingSaberPayloadPB {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct HandwritingSaberDataPB {
    // message fields
    pub view_id: ::std::string::String,
    pub sbn2_bytes: ::std::vec::Vec<u8>,
    pub version: i64,
    pub updated_at: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HandwritingSaberDataPB {
    fn default() -> &'a HandwritingSaberDataPB {
        <HandwritingSaberDataPB as ::protobuf::Message>::default_instance()
    }
}

impl HandwritingSaberDataPB {
    pub fn new() -> HandwritingSaberDataPB {
        ::std::default::Default::default()
    }

    // string view_id = 1;


    pub fn get_view_id(&self) -> &str {
        &self.view_id
    }
    pub fn clear_view_id(&mut self) {
        self.view_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_view_id(&mut self, v: ::std::string::String) {
        self.view_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_view_id(&mut self) -> &mut ::std::string::String {
        &mut self.view_id
    }

    // Take field
    pub fn take_view_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.view_id, ::std::string::String::new())
    }

    // bytes sbn2_bytes = 2;


    pub fn get_sbn2_bytes(&self) -> &[u8] {
        &self.sbn2_bytes
    }
    pub fn clear_sbn2_bytes(&mut self) {
        self.sbn2_bytes.clear();
    }

    // Param is passed by value, moved
    pub fn set_sbn2_bytes(&mut self, v: ::std::vec::Vec<u8>) {
        self.sbn2_bytes = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_sbn2_bytes(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.sbn2_bytes
    }

    // Take field
    pub fn take_sbn2_bytes(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.sbn2_bytes, ::std::vec::Vec::new())
    }

    // int64 version = 3;


    pub fn get_version(&self) -> i64 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i64) {
        self.version = v;
    }

    // int64 updated_at = 4;


    pub fn get_updated_at(&self) -> i64 {
        self.updated_at
    }
    pub fn clear_updated_at(&mut self) {
        self.updated_at = 0;
    }

    // Param is passed by value, moved
    pub fn set_updated_at(&mut self, v: i64) {
        self.updated_at = v;
    }
}

impl ::protobuf::Message for HandwritingSaberDataPB {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.view_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.sbn2_bytes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.version = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.updated_at = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.view_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.view_id);
        }
        if !self.sbn2_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.sbn2_bytes);
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(3, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.updated_at != 0 {
            my_size += ::protobuf::rt::value_size(4, self.updated_at, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.view_id.is_empty() {
            os.write_string(1, &self.view_id)?;
        }
        if !self.sbn2_bytes.is_empty() {
            os.write_bytes(2, &self.sbn2_bytes)?;
        }
        if self.version != 0 {
            os.write_int64(3, self.version)?;
        }
        if self.updated_at != 0 {
            os.write_int64(4, self.updated_at)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HandwritingSaberDataPB {
        HandwritingSaberDataPB::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "view_id",
                |m: &HandwritingSaberDataPB| { &m.view_id },
                |m: &mut HandwritingSaberDataPB| { &mut m.view_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "sbn2_bytes",
                |m: &HandwritingSaberDataPB| { &m.sbn2_bytes },
                |m: &mut HandwritingSaberDataPB| { &mut m.sbn2_bytes },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "version",
                |m: &HandwritingSaberDataPB| { &m.version },
                |m: &mut HandwritingSaberDataPB| { &mut m.version },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "updated_at",
                |m: &HandwritingSaberDataPB| { &m.updated_at },
                |m: &mut HandwritingSaberDataPB| { &mut m.updated_at },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<HandwritingSaberDataPB>(
                "HandwritingSaberDataPB",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static HandwritingSaberDataPB {
        static instance: ::protobuf::rt::LazyV2<HandwritingSaberDataPB> = ::protobuf::rt::LazyV2::INIT;
        instance.get(HandwritingSaberDataPB::new)
    }
}

impl ::protobuf::Clear for HandwritingSaberDataPB {
    fn clear(&mut self) {
        self.view_id.clear();
        self.sbn2_bytes.clear();
        self.version = 0;
        self.updated_at = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HandwritingSaberDataPB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HandwritingSaberDataPB {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SaveHandwritingSaberResponsePB {
    // message fields
    pub new_version: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SaveHandwritingSaberResponsePB {
    fn default() -> &'a SaveHandwritingSaberResponsePB {
        <SaveHandwritingSaberResponsePB as ::protobuf::Message>::default_instance()
    }
}

impl SaveHandwritingSaberResponsePB {
    pub fn new() -> SaveHandwritingSaberResponsePB {
        ::std::default::Default::default()
    }

    // int64 new_version = 1;


    pub fn get_new_version(&self) -> i64 {
        self.new_version
    }
    pub fn clear_new_version(&mut self) {
        self.new_version = 0;
    }

    // Param is passed by value, moved
    pub fn set_new_version(&mut self, v: i64) {
        self.new_version = v;
    }
}

impl ::protobuf::Message for SaveHandwritingSaberResponsePB {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.new_version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.new_version != 0 {
            my_size += ::protobuf::rt::value_size(1, self.new_version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.new_version != 0 {
            os.write_int64(1, self.new_version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SaveHandwritingSaberResponsePB {
        SaveHandwritingSaberResponsePB::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "new_version",
                |m: &SaveHandwritingSaberResponsePB| { &m.new_version },
                |m: &mut SaveHandwritingSaberResponsePB| { &mut m.new_version },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SaveHandwritingSaberResponsePB>(
                "SaveHandwritingSaberResponsePB",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SaveHandwritingSaberResponsePB {
        static instance: ::protobuf::rt::LazyV2<SaveHandwritingSaberResponsePB> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SaveHandwritingSaberResponsePB::new)
    }
}

impl ::protobuf::Clear for SaveHandwritingSaberResponsePB {
    fn clear(&mut self) {
        self.new_version = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SaveHandwritingSaberResponsePB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SaveHandwritingSaberResponsePB {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0eentities.proto\"v\n\x1fCreateHandwritingSaberPayloadPB\x12\x17\n\
    \x07view_id\x18\x01\x20\x01(\tR\x06viewId\x12#\n\x0cinitial_data\x18\x02\
    \x20\x01(\x0cH\0R\x0binitialDataB\x15\n\x13one_of_initial_data\"q\n\x1dS\
    aveHandwritingSaberPayloadPB\x12\x17\n\x07view_id\x18\x01\x20\x01(\tR\
    \x06viewId\x12\x1d\n\nsbn2_bytes\x18\x02\x20\x01(\x0cR\tsbn2Bytes\x12\
    \x18\n\x07version\x18\x03\x20\x01(\x03R\x07version\"\x89\x01\n\x16Handwr\
    itingSaberDataPB\x12\x17\n\x07view_id\x18\x01\x20\x01(\tR\x06viewId\x12\
    \x1d\n\nsbn2_bytes\x18\x02\x20\x01(\x0cR\tsbn2Bytes\x12\x18\n\x07version\
    \x18\x03\x20\x01(\x03R\x07version\x12\x1d\n\nupdated_at\x18\x04\x20\x01(\
    \x03R\tupdatedAt\"A\n\x1eSaveHandwritingSaberResponsePB\x12\x1f\n\x0bnew\
    _version\x18\x01\x20\x01(\x03R\nnewVersionb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
