// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `event_map.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum HandwritingSaberEvent {
    CreateHandwritingSaber = 0,
    OpenHandwritingSaber = 1,
    SaveHandwritingSaber = 2,
    GetHandwritingSaberData = 3,
    CloseHandwritingSaber = 4,
    DeleteHandwritingSaber = 5,
}

impl ::protobuf::ProtobufEnum for HandwritingSaberEvent {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<HandwritingSaberEvent> {
        match value {
            0 => ::std::option::Option::Some(HandwritingSaberEvent::CreateHandwritingSaber),
            1 => ::std::option::Option::Some(HandwritingSaberEvent::OpenHandwritingSaber),
            2 => ::std::option::Option::Some(HandwritingSaberEvent::SaveHandwritingSaber),
            3 => ::std::option::Option::Some(HandwritingSaberEvent::GetHandwritingSaberData),
            4 => ::std::option::Option::Some(HandwritingSaberEvent::CloseHandwritingSaber),
            5 => ::std::option::Option::Some(HandwritingSaberEvent::DeleteHandwritingSaber),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [HandwritingSaberEvent] = &[
            HandwritingSaberEvent::CreateHandwritingSaber,
            HandwritingSaberEvent::OpenHandwritingSaber,
            HandwritingSaberEvent::SaveHandwritingSaber,
            HandwritingSaberEvent::GetHandwritingSaberData,
            HandwritingSaberEvent::CloseHandwritingSaber,
            HandwritingSaberEvent::DeleteHandwritingSaber,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<HandwritingSaberEvent>("HandwritingSaberEvent", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for HandwritingSaberEvent {
}

impl ::std::default::Default for HandwritingSaberEvent {
    fn default() -> Self {
        HandwritingSaberEvent::CreateHandwritingSaber
    }
}

impl ::protobuf::reflect::ProtobufValue for HandwritingSaberEvent {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fevent_map.proto*\xbb\x01\n\x15HandwritingSaberEvent\x12\x1a\n\x16C\
    reateHandwritingSaber\x10\0\x12\x18\n\x14OpenHandwritingSaber\x10\x01\
    \x12\x18\n\x14SaveHandwritingSaber\x10\x02\x12\x1b\n\x17GetHandwritingSa\
    berData\x10\x03\x12\x19\n\x15CloseHandwritingSaber\x10\x04\x12\x1a\n\x16\
    DeleteHandwritingSaber\x10\x05b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
