allprojects {
    repositories {
        google()
        mavenCentral()
        // 添加其他仓库，例如 JitPack
        maven { url 'https://jitpack.io' }
        maven { url 'https://artifact.bytedance.com/repository/AwemeOpenSDK' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}